---

- name: update
  apt:
      update_cache: yes
  become: yes
  tags: update
- name: upgrade
  apt:
      upgrade: yes
  become: yes
  tags: update
- name: upgrade dist
  apt:
      upgrade: dist
  become: yes
  tags: update
- name: use apt to install mariadb 
  apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
  vars:
      packages:
          - mariadb-server
          - mariadb-client
  become: yes
  tags: install
- name: start MariaDB 
  shell: "{{ item }}"
  loop:
      - systemctl stop mariadb.service
      - systemctl start mariadb.service
      - systemctl enable mariadb.service
  become: yes
- name: Adds Python MySQL support on Debian/Ubuntu
    apt:
      name: python-mysqldb
      state: latest
  become: yes
  tags: secure
- name: 1. set mysql root pass
  mysql_user:
      login_user: root
      login_password: "{{ msi_mysql_root_pass }}"
      user: root
      host_all: yes
      password: "{{ msi_new_mysql_root_pass }}"
  become: yes
- name: 3. remove anonymous users
  mysql_user:
      login_user: root
      login_password: "{{ msi_new_mysql_root_pass }}"
      user: ''
      host_all: yes
      state: absent
  become: yes
- name: 4. remove test database
  mysql_db:
      login_user: root
      login_password: "{{ msi_new_mysql_root_pass }}"
      db: test
      state: absent
  become: yes
  register: remove_testdb
- name: 4.1 remove test database priviledges
  block:
    - shell: >
        mysql -u root -p{{ msi_new_mysql_root_pass }}
        -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"
    - shell: mysql -u root -p{{ msi_new_mysql_root_pass }} -e "FLUSH PRIVILEGES"
  when: remove_testdb is changed
  become: yes

