---

- name: update
  apt:
      update_cache: yes
  become: yes
  tags: update
- name: upgrade
  apt:
      upgrade: yes
  become: yes
  tags: update
- name: upgrade dist
  apt:
      upgrade: dist
  become: yes
  tags: update
- name: use apt to install mariadb 
  apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
  vars:
      packages:
          - mariadb-server
          - mariadb-client
  become: yes
  tags: install
- name: start MariaDB 
  shell: "{{ item }}"
  loop:
      - systemctl stop mariadb.service
      - systemctl start mariadb.service
      - systemctl enable mariadb.service
  become: yes
- name: Adds Python MySQL support on Debian/Ubuntu
    apt: pkg="python-mysqldb" state=present
      when: ansible_os_family == 'Debian'
- name: Set the root password 
    mysql_user: login_user=root login_password= "{{ root_password }}" user=root password= "{{ root_password }}"
- name: Secure the root user for IPV6 localhost (::1)
    mysql_user: login_user=root login_password= "{{ root_password }}" user=root password= "{{ root_password }}" host="::1"
- name: Secure the root user for IPV4 localhost (127.0.0.1)
    mysql_user: login_user=root login_password= "{{ root_password }}" user=root password= "{{ root_password }}" host="127.0.0.1"
- name: Secure the root user for localhost domain
    mysql_user: login_user=root login_password= "{{ root_password }}" user=root password= "{{ root_password }}" host="localhost"
- name: Secure the root user for server_hostname domain
    mysql_user: login_user=root login_password= "{{ root_password }}" user=root password= "{{ root_password }}" host= "{{ ansible_fqdn }}"
- name: Deletes anonymous server user
    mysql_user: login_user=root login_password= "{{ root_password }}" user="" host_all=yes state=absent
- name: Removes the test database
    mysql_db: login_user=root login_password= "{{ root_password }}" db=test state=absent
